# Generated by Django 5.2.7 on 2025-10-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='twxt',
            new_name='text',
        ),
    ]
